config/routes.rb
WebScrapper::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :items

  resources :targets

  resources :just_dial_targets

end

app/models/item.rb
#
#
# User: Simar Paul Singh
# Date: 5/20/12
# Time: 3:22 PM
#
class Item < ActiveRecord::Base
  belongs_to :container, :polymorphic => true, :dependent => :destroy
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end

  private

  def find_container
  params.each do |name, value|
    if name =~ /(.+)_id$/
      return $1.classify.constantize.find(value)
    end
  end
  nil
end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_area :contact %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_area :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_area :detail %>
  </div>
  <div class="field">
    <%= f.label :source   %><br />
    <%= f.text_area :source %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_area :link %>
  </div>
  <div class="field">
    <%= f.label :container_id %><br />
    <%= f.number_field :container_id %>
  </div>
  <div class="field">
    <%= f.label :container_type %><br />
    <%= f.text_field :container_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>Phone</th>
    <th>Website</th>
    <th>Address</th>
    <th>Link</th>
    <th>Description</th>
    <!--<th>Detail</th>-->
    <th>Source</th>
    <th>Container</th>
    <th>Container type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.contact %></td>
    <td><%= item.phone %></td>
    <td><%= link_to item.website , 'http://' + item.website.squish[0..-3] , :target => "_blank" %></td>
    <td><%= item.address %></td>
    <td><%= link_to 'link', item.link , :target => "_blank" %></td>
    <td><%= item.description %></td>
    <!--<td><%= item.detail %></td>-->
    <td><%= item.source %></td>
    <td><%= item.container_id %></td>
    <td><%= item.container_type %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Contact:</b>
  <%= @item.contact %>
</p>

<p>
  <b>Link:</b>
  <%= @item.link %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Detail:</b>
  <%= @item.detail %>
</p>

<p>
  <b>Source:</b>
  <%= @item.source %>
</p>

<p>
  <b>Container:</b>
  <%= @item.container_id %>
</p>

<p>
  <b>Container type:</b>
  <%= @item.container_type %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>