config/routes.rb
WebScrapper::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :items

  resources :targets

  resources :just_dial_targets

end

app/models/just_dial_target.rb
#
# Created by JetBrains RubyMine.
# User: Simar Singh
# Date: 6/17/12
# Time: 2:32 AM
#

class JustDialTarget < Target
  after_validation :build_locations_script

  def build_locations_script
      self.location = JustDialTarget.create_location_script(url,num_of_pages);
  end

  def self.create_location_script(url,num_of_pages)
       sites = []
      (1..num_of_pages).each do |i|
          sites << "#{url}/page-#{i.to_s}"
          end
      sites.to_s
  end

end

app/controllers/just_dial_targets_controller.rb
class JustDialTargetsController < ApplicationController
  # GET /just_dial_targets
  # GET /targets.json
  def index
    @targets = JustDialTarget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @targets }
    end
  end

  # GET /just_dial_targets/1
  # GET /just_dial_targets/1.json
  def show
    @target = JustDialTarget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @target }
    end
  end

  # GET /just_dial_targets/new
  # GET /just_dial_targets/new.json
  def new
    @target = JustDialTarget.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @target }
    end
  end

  # GET /just_dial_targets/1/edit
  def edit
    @target = JustDialTarget.find(params[:id])
  end

  # POST /just_dial_targets
  # POST /just_dial_targets.json
  def create
    @target = JustDialTarget.new(params[:target])
    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render json: @target, status: :created, location: @target }
      else
        format.html { render action: "new" }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /just_dial_targets/1
  # PUT /just_dial_targets/1.json
  def update
    @target = JustDialTarget.find(params[:id])
    respond_to do |format|
      if @target.update_attributes(params[:target])
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /just_dial_targets/1
  # DELETE /just_dial_targets/1.json
  def destroy
    @target = JustDialTarget.find(params[:id])
    @target.destroy

    respond_to do |format|
      format.html { redirect_to just_dial_targets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/just_dial_targets_helper.rb
module JustDialTargetsHelper
end

app/views/just_dial_targets/_form.html.erb
<%= form_for(@target) do |f| %>
  <% if @target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% @target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <!--%= f.text_field :name %-->
    <input id="target_name" name="target[name]" size="30" type="text" />
  </div>

  <div class="field">
    <%= f.label "Url ex (http://www.justdial.com/Delhi/Pizza-%3Cnear%3E-KESHAV-PURAM)" %><br />
    <!--%= f.text_field :url %-->
    <input id="target_url" name="target[url]" size="30" type="text" />
  </div>

  <div class="field">
    <%= f.label :num_of_pages %><br />
    <!--%= f.text_field :num_of_pages %-->
    <input id="target_num_of_pages" name="target[num_of_pages]" size="30" type="text" />
  </div>


  <div class="field">
    <%= f.label :lead_source %><br />
    <select id="target_lead_source" name="target[lead_source]">
      <option value="Existing Customer" >	Existing Customer	</option>
      <option value="Self Generated" >	Self Generated	</option>
      <option value="Employee" >	Employee	</option>
      <option value="Partner" >	Partner	</option>
      <option value="Public Relations" >	Public Relations	</option>
      <option value="Direct Mail" >	Direct Mail	</option>
      <option value="Conference" >	Conference	</option>
      <option value="Trade Show" >	Trade Show	</option>
      <option value="Word of mouth" >	Word of mouth	</option>
      <option value="Other" >	Other	</option>
      <option value="Friends Contact" >	Friends Contact	</option>
      <option value="India Mart" >	India Mart	</option>
      <option value="Just Dial" selected>	Just Dial	</option>
      <option value="News Paper" >	News Paper	</option>
      <option value="Online Voucher" >	Online Voucher	</option>
      <option value="Sulekha" >	Sulekha	</option>
      <option value="Yellow Pages" >	Yellow Pages	</option>
      <option value="Haatopia Website" >	Haatopia Website	</option>

    </select>
    <!-- %= f.text_field :lead_source %-->
  </div>

  <div class="field">
    <%= f.label :industry %><br />
    <!--%= f.text_field :industry %-->
    <select id="target_industry" name="target[industry]">
      <option value="0" >     Please Select	</option>
      <option value="Advertising Agencies">Advertising Agencies</option>
      <option value="Aerobic Classes">Aerobic Classes</option>
      <option value="Animal Care Services">Animal Care Services</option>
      <option value="Antiques Collectibles">Antiques Collectibles</option>
      <option value="Apartment Hotels">Apartment Hotels</option>
      <option value="Architects">Architects</option>
      <option value="Art Galleries">Art Galleries</option>
      <option value="Arts & Crafts">Arts & Crafts</option>
      <option value="Astrology">Astrology</option>
      <option value="Automobile Rentals">Automobile Rentals</option>
      <option value="Bakeries">Bakeries</option>
      <option value="Beauty Salons & Spa">Beauty Salons & Spa</option>
      <option value="Boarding Schools">Boarding Schools</option>
      <option value="Boutiques">Boutiques</option>
      <option value="Business & Professional Associations">Business & Professional Associations</option>
      <option value="Car Rental">Car Rental</option>
      <option value="Caterers">Caterers</option>
      <option value="Cctv Dealers">Cctv Dealers</option>
      <option value="Child Care">Child Care</option>
      <option value="Choreographers">Choreographers</option>
      <option value="Cleaning Services">Cleaning Services</option>
      <option value="Clubs">Clubs</option>
      <option value="Coaching Classes">Coaching Classes</option>
      <option value="Community">Community</option>
      <option value="Company Website">Company Website</option>
      <option value="Compter Sales Services">Compter Sales Services</option>
      <option value="Consultants">Consultants</option>
      <option value="Consulting">Consulting</option>
      <option value="Cookery Classes">Cookery Classes</option>
      <option value="Dance Classes">Dance Classes</option>
      <option value="Dentist">Dentist</option>
      <option value="Detective Agencies">Detective Agencies</option>
      <option value="Education">Education</option>
      <option value="Electronics">Electronics</option>
      <option value="Entertainment">Entertainment</option>
      <option value="Event Management">Event Management</option>
      <option value="Fashion Designing">Fashion Designing</option>
      <option value="Finance">Finance</option>
      <option value="Fitness Centre">Fitness Centre</option>
      <option value="Flowers">Flowers</option>
      <option value="Food & Drinks">Food & Drinks</option>
      <option value="Furniture">Furniture</option>
      <option value="Gift Shops">Gift Shops</option>
      <option value="Government">Government</option>
      <option value="Guitar Dealers">Guitar Dealers</option>
      <option value="Gymnasiums">Gymnasiums</option>
      <option value="Gynaecologists">Gynaecologists</option>
      <option value="Healthcare">Healthcare</option>
      <option value="Hobby Classes">Hobby Classes</option>
      <option value="Home Furnishing">Home Furnishing</option>
      <option value="Homeopathic">Homeopathic</option>
      <option value="Hospitality">Hospitality</option>
      <option value="Hostels">Hostels</option>
      <option value="Hotel">Hotel</option>
      <option value="House Keeping Services">House Keeping Services</option>
      <option value="Insurance">Insurance</option>
      <option value="Interior Design">Interior Design</option>
      <option value="Janitorial Supplies">Janitorial Supplies</option>
      <option value="Lawyer">Lawyer</option>
      <option value="Lifestyle">Lifestyle</option>
      <option value="Lodging Services">Lodging Services</option>
      <option value="Massage Centres">Massage Centres</option>
      <option value="Matrimonial Bureaus">Matrimonial Bureaus</option>
      <option value="Music Classes">Music Classes</option>
      <option value="Not For Profit">Not For Profit</option>
      <option value="Orchestras">Orchestras</option>
      <option value="Other">Other</option>
      <option value="Packer and Mover">Packer and Mover</option>
      <option value="Painting & Wallpaper Services">Painting & Wallpaper Services</option>
      <option value="Pest Control Services">Pest Control Services</option>
      <option value="Pets & Accessories">Pets & Accessories</option>
      <option value="Photographers">Photographers</option>
      <option value="Physiotherapists">Physiotherapists</option>
      <option value="Placements & Careers">Placements & Careers</option>
      <option value="Plant Nurseries">Plant Nurseries</option>
      <option value="Power Yoga Classes">Power Yoga Classes</option>
      <option value="Pre School">Pre School</option>
      <option value="Real Estate">Real Estate</option>
      <option value="Retail">Retail</option>
      <option value="Sales And Exhibitions">Sales And Exhibitions</option>
      <option value="Security Services">Security Services</option>
      <option value="Shopping Centers">Shopping Centers</option>
      <option value="Singing Classes">Singing Classes</option>
      <option value="Specialty Shops">Specialty Shops</option>
      <option value="Sporting Goods">Sporting Goods</option>
      <option value="Summer Camps">Summer Camps</option>
      <option value="Swimming Classes">Swimming Classes</option>
      <option value="Swimming Pools">Swimming Pools</option>
      <option value="Tour and Travel">Tour and Travel</option>
      <option value="Trophies Plaques">Trophies Plaques</option>
      <option value="Video Audio Services">Video Audio Services</option>
      <option value="Waste Management">Waste Management</option>
      <option value="Water Parks">Water Parks</option>
      <option value="Wedding">Wedding</option>
      <option value="Yoga Classes">Yoga Classes</option>
  </select>
  </div>

  <div class="field">
    <%= f.label :city %><br />
    <!--%= f.text_field :city %-->
    <select  id="target_city" name="target[city]" >
      <option value="0" >     Please Select	</option>
      <option value="Delhi">Delhi</option>
      <option value="Indore">Indore</option>
      <option value="Jaipur">Jaipur</option>
      <option value="Pune">Pune</option>
      <option value="Mumbai">Mumbai</option>

    </select>
  </div>

  <div class="field">
    <%= f.label :state %><br />
    <!--%= f.text_field :state %-->
    <select id="target_state" name="target[state]" >
      <option value="0" >     Please Select	</option>
      <option value="Maharastra">Maharastra</option>
      <option value="Madhya Pradesh">Madhya Pradesh</option>
      <option value="Delhi">Delhi</option>
      <option value="Rajasthan">Rajasthan</option>
    </select>
  </div>


 <div class="field">
   <%= f.label :country %><br />
   <%= f.text_field :country %>
  </div>

 <div class="field">
   <%= f.label :assigned_to %><br />
   <%= f.text_field :assigned_to %>
 </div>

 <div class="actions">
    <%= f.submit %>
 </div>
<% end %>

app/views/just_dial_targets/edit.html.erb
<h1>Editing target</h1>

<%= render 'form' %>

<%= link_to 'Show', @target %> |
<%= link_to 'Back', just_dial_targets_path %>

app/views/just_dial_targets/index.html.erb
<h1>Listing targets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Script</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @targets.each do |target| %>
  <tr>
    <td><%= target.name %></td>
    <td><%= target.location %></td>
    <td><%= target.script %></td>
    <td><%= target.description %></td>
    <td><%= link_to 'Show', target %></td>
    <td><%= link_to 'Edit', edit_target_path(target) %></td>
    <td><%= link_to 'Destroy', target, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Target', new_just_dial_target_path %>

app/views/just_dial_targets/new.html.erb
<h1>New target</h1>

<%= render 'form' %>

<%= link_to 'Back', just_dial_targets_path %>

app/views/just_dial_targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @target.name %>
</p>

<p>
  <b>Location:</b>
  <pre class="code">
    <%= @target.location %>
  </pre>
</p>

<p>
  <b>Script:</b>
  <pre class="code">
    <%= @target.script %>
  </pre>

</p>

<p>
  <b>Description:</b>
  <%= @target.description %>
</p>


<%= link_to 'Edit', edit_just_dial_target_path(@target) %> |
<%= link_to 'Back', just_dial_targets_path %>